# version: "3.7"

# services:
#   inventory-system:
#     image: node:alpine
#     container_name: inventory-system
#     entrypoint: /bin/sh
#     ports:
#       - 8004:8000
#     working_dir: /frontend/inventory-system
#     volumes:
#       - type: bind
#         source: ./
#         target: /frontend/inventory-system
#     tty: true
#http://localhost:8004/